version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    pre-build:
      commands:
        - echo In pre_build phase
        - mvn test
    build:
       commands:
        - echo In build phase
        - mvn package -DskipTests=true
    post-build:
       commands:
        - echo In post-build phase 
artifacts:
  files:
    - "target/*.jar"
  discard-paths: yes #pour ne pas prendre en compte le target dans le nom 